# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stepperMotor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main = QtWidgets.QWidget(self.centralwidget)
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top = QtWidgets.QWidget(self.main)
        self.top.setMaximumSize(QtCore.QSize(16777215, 75))
        self.top.setStyleSheet("background-color:black")
        self.top.setObjectName("top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.top)
        self.label.setMinimumSize(QtCore.QSize(350, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:white")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.top)
        self.bottom = QtWidgets.QWidget(self.main)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.bottom)
        self.widget_4.setMinimumSize(QtCore.QSize(500, 80))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.widget_4.setStyleSheet("background-color:white\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_frame = QtWidgets.QFrame(self.widget_4)
        self.left_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.left_frame.setMaximumSize(QtCore.QSize(1000, 1000))
        self.left_frame.setStyleSheet("background-color:black")
        self.left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 50)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(325, 380))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(1000, 1000))
        self.plainTextEdit.setStyleSheet("background-color:white")
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.start_stop_btn = QtWidgets.QPushButton(self.left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_stop_btn.sizePolicy().hasHeightForWidth())
        self.start_stop_btn.setSizePolicy(sizePolicy)
        self.start_stop_btn.setMinimumSize(QtCore.QSize(150, 60))
        self.start_stop_btn.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.start_stop_btn.setFont(font)
        self.start_stop_btn.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#b33a22;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 4px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.start_stop_btn.setObjectName("start_stop_btn")
        self.verticalLayout_3.addWidget(self.start_stop_btn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.left_frame)
        self.right_frame = QtWidgets.QFrame(self.widget_4)
        self.right_frame.setMinimumSize(QtCore.QSize(410, 0))
        self.right_frame.setMaximumSize(QtCore.QSize(1000, 1000))
        self.right_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.right_top = QtWidgets.QFrame(self.right_frame)
        self.right_top.setMinimumSize(QtCore.QSize(450, 0))
        self.right_top.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.right_top.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.right_top.setStyleSheet("background-color:black")
        self.right_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_top.setObjectName("right_top")
        self.gridLayout = QtWidgets.QGridLayout(self.right_top)
        self.gridLayout.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.deactivate = QtWidgets.QLabel(self.right_top)
        self.deactivate.setMinimumSize(QtCore.QSize(250, 70))
        self.deactivate.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deactivate.setFont(font)
        self.deactivate.setStyleSheet("background-color:#b33a22;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 4px")
        self.deactivate.setScaledContents(True)
        self.deactivate.setAlignment(QtCore.Qt.AlignCenter)
        self.deactivate.setWordWrap(False)
        self.deactivate.setObjectName("deactivate")
        self.gridLayout.addWidget(self.deactivate, 1, 0, 1, 1)
        self.activate = QtWidgets.QLabel(self.right_top)
        self.activate.setMinimumSize(QtCore.QSize(250, 70))
        self.activate.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.activate.setFont(font)
        self.activate.setAcceptDrops(False)
        self.activate.setToolTipDuration(-1)
        self.activate.setAutoFillBackground(False)
        self.activate.setStyleSheet("background-color:#b33a22;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 4px")
        self.activate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.activate.setLineWidth(1)
        self.activate.setScaledContents(True)
        self.activate.setAlignment(QtCore.Qt.AlignCenter)
        self.activate.setWordWrap(False)
        self.activate.setObjectName("activate")
        self.gridLayout.addWidget(self.activate, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.right_top)
        self.right_bottom = QtWidgets.QFrame(self.right_frame)
        self.right_bottom.setMinimumSize(QtCore.QSize(450, 0))
        self.right_bottom.setMaximumSize(QtCore.QSize(16777215, 180))
        self.right_bottom.setStyleSheet("background-color:black")
        self.right_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_bottom.setObjectName("right_bottom")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.right_bottom)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.left_button = QtWidgets.QPushButton(self.right_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_button.sizePolicy().hasHeightForWidth())
        self.left_button.setSizePolicy(sizePolicy)
        self.left_button.setMinimumSize(QtCore.QSize(150, 60))
        self.left_button.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.left_button.setFont(font)
        self.left_button.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#b33a22;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 4px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.left_button.setObjectName("left_button")
        self.gridLayout_2.addWidget(self.left_button, 0, 0, 1, 1)
        self.right_button = QtWidgets.QPushButton(self.right_bottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_button.sizePolicy().hasHeightForWidth())
        self.right_button.setSizePolicy(sizePolicy)
        self.right_button.setMinimumSize(QtCore.QSize(150, 60))
        self.right_button.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.right_button.setFont(font)
        self.right_button.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#b33a22;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 4px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.right_button.setObjectName("right_button")
        self.gridLayout_2.addWidget(self.right_button, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.right_bottom)
        self.horizontalLayout.addWidget(self.right_frame)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.bottom)
        self.verticalLayout.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Stepper Motor Test App"))
        self.start_stop_btn.setText(_translate("MainWindow", "Stop"))
        self.deactivate.setText(_translate("MainWindow", "Sensor Deactivate"))
        self.activate.setText(_translate("MainWindow", "Sensor Activate"))
        self.left_button.setText(_translate("MainWindow", "Left"))
        self.right_button.setText(_translate("MainWindow", "Right"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
