# Form implementation generated from reading ui file 'PWM.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PWM(object):
    def setupUi(self, PWM):
        PWM.setObjectName("PWM")
        PWM.resize(400, 300)
        self.label = QtWidgets.QLabel(PWM)
        self.label.setGeometry(QtCore.QRect(20, 50, 71, 20))
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PWM)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(PWM)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 101, 16))
        self.label_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(PWM)
        self.textEdit.setGeometry(QtCore.QRect(150, 130, 241, 31))
        self.textEdit.setObjectName("textEdit")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(PWM)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(150, 90, 241, 16))
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.horizontalScrollBar = QtWidgets.QScrollBar(PWM)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(150, 50, 241, 16))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")

        self.retranslateUi(PWM)
        QtCore.QMetaObject.connectSlotsByName(PWM)

    def retranslateUi(self, PWM):
        _translate = QtCore.QCoreApplication.translate
        PWM.setWindowTitle(_translate("PWM", "Dialog"))
        self.label.setText(_translate("PWM", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">DutyCycle</span></p></body></html>"))
        self.horizontalScrollBar.sliderMoved.connect(self.sliderval1)
        self.label_2.setText(_translate("PWM", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Frequency</span></p></body></html>"))
        self.horizontalScrollBar_2.sliderMoved.connect(self.sliderval2)
        self.label_3.setText(_translate("PWM", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Pin Number</span></p></body></html>"))

    def sliderval1(self):
        self.horizontalScrollBar.setMaximum(100)
        self.textEdit.setText(str(self.horizontalScrollBar.value()))
    
    def sliderval2(self):
        self.horizontalScrollBar_2.setMaximum(100)
        self.textEdit.setText(str(self.horizontalScrollBar_2.value()))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PWM = QtWidgets.QDialog()
    ui = Ui_PWM()
    ui.setupUi(PWM)
    PWM.show()
    sys.exit(app.exec())
