# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Detail(object):
    def setupUi(self, Detail):
        Detail.setObjectName("Detail")
        Detail.resize(977, 950)
        self.label = QtWidgets.QLabel(Detail)
        self.label.setGeometry(QtCore.QRect(20, 20, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Detail)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 931, 600))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Detail)
        QtCore.QMetaObject.connectSlotsByName(Detail)

    def retranslateUi(self, Detail):
        _translate = QtCore.QCoreApplication.translate
        Detail.setWindowTitle(_translate("Detail", "User Detail"))
        self.label.setText(_translate("Detail", "Welcome Dear "))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Detail", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Detail", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Detail", "Subject ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Detail", "UserID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Detail", "Total Numbers"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Detail", "Marks Obtained"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Detail", "Result"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Detail", "Remarks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Detail = QtWidgets.QDialog()
    ui = Ui_Detail()
    ui.setupUi(Detail)
    Detail.show()
    sys.exit(app.exec_())
